### ISSUE TITLE
Upgrades are coming

### ISSUE THREAD

**Issue by maxwondercorn** [Glavin001/ember-c3#77]
This issue addresses upcoming changes to ember-c3 and opens a discussion on possible future features.  It will also be used as a tracker.

Most of the items proposed are already in existing PRs or forks. This issue spells out the major changes that are mostly complete, in progress or planned.  Please provide feedback.  Help is welcome

- [x] Merge PRs #64 and #69
- [x] Move C3 from Bower to NPM - (pr #75)
- [x] Create a minimal set of tests (pr #79) - rendering tests
- [x] chart event tests (pr #82)
- [x] data event tests (pr #82)
- [x] Bump c3 to latest version (pr #79)
- [x] Upgrade ember to more current version.  The current version is on 1.13, the latest LTS is now 3.4.  
 PR #75 upgrades to version 3.1 and the fork is on 3.3. The preference would be 3.4 LTS which would work down to ember 2.4 (pr #79 - v3.3) (pr #83)
- [x] Expose the c3 chart as a component property.  This would allow advanced use of c3 without adding a lot of additional properties to the component.  In some instances, this may not be DDAU but creates a larger API for edge cases (fork)
- [x] Update the README/documentation to reflect changes and new component properties (pr #79)
- [x] Add additional examples of using c3. Many of the issues raised are how to do something in c3
with the addon.  In many cases, changing how data is presented to the component will make the graphs look or work differently.  Most of the c3 documentation examples can already be done with the addon
- [x] Update gh-pages demo app with new dummy app.  Change readme as needed to point to new exampes

After these changes are completed the remaining open PRs will be closed.  Some of the features are included in other PRs or the PRs may no longer be needed.  Updated and new PRs are welcome after the next version is published.

Issues that are resolved with the updates will be closed. Due to the age, most others will be closed with a note pointing to the new version(s) and they can resubmit if the issue still exists.

**Future**
This is a request for future ideas...

**Comment by bravo-kernel** [comment]
This upgrade would be awesome and I will immediately switch back to using ember-c3 inside ember-tabler once it is done 💯

**Comment by Glavin001** [comment]
@maxwondercorn let me know what your npm username is so I can give you publish permissions :). 🎉 
https://www.npmjs.com/package/ember-c3

**Comment by maxwondercorn** [comment]
@Glavin001 I think I already have it, but username is gmartell if not

**Comment by Glavin001** [comment]
@maxwondercorn: confirmed! You do have access 👍 .

**Comment by maxwondercorn** [comment]
The two major PRs have been merged and 11 issues have been closed.  If anyone wants to try and/or test the changes you can install directly from GitHub with directions found [here](https://ember-cli.com/extending/#using-a-private-repository).  Rendering test have passed from ember 2.4 through Canary

**Comment by maxwondercorn** [comment]
The internal error logic was refactored out so there is nothing to expose.  The following tasks were removed from the upgrade list.

- Add ability to trigger an action on c3 error - expose internal error function (fork)
- Document using error trigger

**Comment by maxwondercorn** [comment]
The updated addon has been released as v1.0.0 - will work with ember-cli 2.13 and above

**Comment by maxwondercorn** [comment]
The upgrade issue is being closed.  Open new issues for bugs or future ideas as needed
